import { Mic, Newspaper, TrendingUp, Award, Users, DollarSign, Play, ExternalLink } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

const OurImpact = () => {
  const impactMetrics = [
    { 
      icon: DollarSign, 
      number: "$2.3B", 
      label: "Member Revenue Generated",
      description: "Collective revenue generated by member companies in the last year"
    },
    { 
      icon: Users, 
      number: "15,000+", 
      label: "Jobs Created",
      description: "Direct employment opportunities created by our member companies"
    },
    { 
      icon: TrendingUp, 
      number: "89%", 
      label: "Business Growth Rate",
      description: "Of members report significant business growth within 18 months"
    },
    { 
      icon: Award, 
      number: "450+", 
      label: "Awards & Recognition",
      description: "Industry awards and recognition received by our members"
    },
  ];

  const newsStories = [
    {
      date: "Dec 10, 2024",
      category: "Press Release",
      title: "GD Power House Launches Global Mentorship Program",
      excerpt: "New initiative connects experienced entrepreneurs with rising stars across 15 chapters worldwide.",
      readTime: "3 min read"
    },
    {
      date: "Dec 8, 2024",
      category: "Member Success",
      title: "Chapter Member Raises $50M Series B Funding",
      excerpt: "Sarah Chen's fintech startup achieves unicorn status with support from GD Power House network.",
      readTime: "5 min read"
    },
    {
      date: "Dec 5, 2024",
      category: "Community",
      title: "Annual Impact Report: Record-Breaking Year of Growth",
      excerpt: "2024 marks our most successful year with 40% membership growth and unprecedented member achievements.",
      readTime: "8 min read"
    },
    {
      date: "Dec 1, 2024",
      category: "Partnership",
      title: "Strategic Alliance with Global Innovation Labs",
      excerpt: "New partnership provides members with access to cutting-edge technology and R&D resources.",
      readTime: "4 min read"
    },
    {
      date: "Nov 28, 2024",
      category: "Events",
      title: "Global Summit 2024: Breaking Barriers Together",
      excerpt: "Over 1,000 entrepreneurs gathered virtually for our largest event, featuring industry leaders and breakthrough sessions.",
      readTime: "6 min read"
    },
    {
      date: "Nov 25, 2024",
      category: "Awards",
      title: "GD Power House Named 'Community of the Year'",
      excerpt: "Recognized by Entrepreneur Magazine for outstanding contribution to global entrepreneurship ecosystem.",
      readTime: "3 min read"
    }
  ];

  const podcasts = [
    {
      title: "From Startup to Scale: The Complete Journey",
      host: "David Rodriguez",
      guest: "Emma Watson, CEO of TechFlow",
      duration: "42 min",
      downloads: "15.2K",
      description: "Emma shares her journey from college dropout to leading a $100M company, including the pivotal role of community support.",
      topics: ["Scaling", "Leadership", "Funding"]
    },
    {
      title: "Breaking into International Markets",
      host: "Alex Thompson",
      guest: "Marcus Chen, Founder of GlobalReach",
      duration: "38 min",
      downloads: "12.8K",
      description: "Marcus reveals his strategy for expanding into 12 countries and the cultural insights that made the difference.",
      topics: ["International", "Strategy", "Culture"]
    },
    {
      title: "The Future of Entrepreneurship with AI",
      host: "Sarah Chen",
      guest: "Dr. Priya Patel, AI Researcher & Entrepreneur",
      duration: "45 min",
      downloads: "18.7K",
      description: "Dr. Patel discusses how AI is transforming entrepreneurship and what tomorrow's business leaders need to know.",
      topics: ["AI", "Future", "Innovation"]
    },
    {
      title: "Sustainable Business: Profit with Purpose",
      host: "David Rodriguez",
      guest: "Tom Green, CEO of EcoVentures",
      duration: "40 min",
      downloads: "11.5K",
      description: "Tom explains how sustainable practices drove his company to profitability while making a positive environmental impact.",
      topics: ["Sustainability", "Purpose", "Impact"]
    },
    {
      title: "Women in Entrepreneurship: Breaking Glass Ceilings",
      host: "Sarah Chen",
      guest: "Lisa Johnson, Serial Entrepreneur",
      duration: "35 min",
      downloads: "14.3K",
      description: "Lisa shares her experience breaking into male-dominated industries and building a billion-dollar company.",
      topics: ["Women", "Leadership", "Diversity"]
    },
    {
      title: "Failure to Success: The Comeback Story",
      host: "Alex Thompson",
      guest: "Robert Kim, Founder of Phoenix Ventures",
      duration: "50 min",
      downloads: "16.9K",
      description: "Robert's candid discussion about losing everything and building back stronger with community support.",
      topics: ["Resilience", "Failure", "Recovery"]
    }
  ];

  const getCategoryColor = (category: string) => {
    switch (category) {
      case "Press Release": return "bg-primary text-primary-foreground";
      case "Member Success": return "bg-secondary text-secondary-foreground";
      case "Community": return "bg-accent text-accent-foreground";
      case "Partnership": return "bg-muted text-muted-foreground";
      case "Events": return "bg-orange-500 text-white";
      case "Awards": return "bg-green-500 text-white";
      default: return "bg-muted text-muted-foreground";
    }
  };

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-primary to-primary-deep text-primary-foreground py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-5xl md:text-6xl font-hero mb-6 animate-fade-in-up">
              Our Impact
            </h1>
            <p className="text-xl md:text-2xl font-subheading mb-8 opacity-90">
              Measuring success through member achievements and community growth
            </p>
            <div className="flex flex-wrap justify-center gap-6 text-sm font-medium">
              <div className="flex items-center gap-2">
                <Newspaper className="w-5 h-5" />
                <span>Latest News & Updates</span>
              </div>
              <div className="flex items-center gap-2">
                <Mic className="w-5 h-5" />
                <span>Inspiring Podcasts</span>
              </div>
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5" />
                <span>Real Impact Metrics</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Impact Metrics */}
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-heading mb-4">By The Numbers</h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Our community's collective success tells the story of what's possible when 
              entrepreneurs support each other
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {impactMetrics.map((metric) => (
              <Card key={metric.label} className="p-6 text-center hover:shadow-medium transition-all duration-300 hover:scale-105">
                <CardContent className="p-0">
                  <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                    <metric.icon className="w-8 h-8 text-primary" />
                  </div>
                  <div className="text-3xl font-bold text-primary mb-2">{metric.number}</div>
                  <h3 className="font-heading mb-3">{metric.label}</h3>
                  <p className="text-sm text-muted-foreground">{metric.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Newsroom */}
      <section className="py-20 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-heading mb-4">Newsroom</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Stay updated with the latest announcements, member successes, and community highlights
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-7xl mx-auto">
            {newsStories.map((story, index) => (
              <Card key={index} className="overflow-hidden hover:shadow-medium transition-all duration-300 hover:scale-105">
                <CardContent className="p-6">
                  <div className="flex items-center justify-between mb-4">
                    <Badge className={getCategoryColor(story.category)}>
                      {story.category}
                    </Badge>
                    <span className="text-sm text-muted-foreground">{story.readTime}</span>
                  </div>
                  
                  <h3 className="font-heading text-lg mb-3 line-clamp-2">{story.title}</h3>
                  <p className="text-muted-foreground text-sm mb-4 line-clamp-3">{story.excerpt}</p>
                  
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground">{story.date}</span>
                    <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                      <ExternalLink className="w-4 h-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="text-center mt-12">
            <Button size="lg">
              View All News Stories
            </Button>
          </div>
        </div>
      </section>

      {/* Podcasts */}
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-heading mb-4">Power House Podcasts</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Deep conversations with successful entrepreneurs sharing their journeys, insights, and lessons learned
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
            {podcasts.map((podcast, index) => (
              <Card key={index} className="overflow-hidden hover:shadow-medium transition-all duration-300">
                <CardContent className="p-6">
                  <div className="flex items-start gap-4">
                    <div className="w-16 h-16 bg-primary/10 rounded-lg flex items-center justify-center flex-shrink-0">
                      <Play className="w-8 h-8 text-primary" />
                    </div>
                    
                    <div className="flex-1">
                      <h3 className="font-heading text-lg mb-2">{podcast.title}</h3>
                      <p className="text-sm text-muted-foreground mb-2">
                        Host: <span className="font-medium">{podcast.host}</span> • 
                        Guest: <span className="font-medium">{podcast.guest}</span>
                      </p>
                      <p className="text-sm mb-3">{podcast.description}</p>
                      
                      <div className="flex flex-wrap gap-2 mb-4">
                        {podcast.topics.map((topic) => (
                          <Badge key={topic} variant="outline" className="text-xs">
                            {topic}
                          </Badge>
                        ))}
                      </div>
                      
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-4 text-sm text-muted-foreground">
                          <span>{podcast.duration}</span>
                          <span>{podcast.downloads} downloads</span>
                        </div>
                        <Button size="sm">
                          <Play className="w-4 h-4 mr-2" />
                          Listen
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="text-center mt-12">
            <Button size="lg" variant="outline">
              <Mic className="w-5 h-5 mr-2" />
              Explore All Episodes
            </Button>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-accent to-primary text-accent-foreground">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-heading mb-6">
            Be Part of the Impact
          </h2>
          <p className="text-xl mb-8 opacity-90 max-w-2xl mx-auto">
            Join our community and start creating your own success story worth sharing
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" variant="secondary">
              Share Your Story
            </Button>
            <Button size="lg" variant="outline" className="bg-transparent border-accent-foreground text-accent-foreground hover:bg-accent-foreground hover:text-accent">
              Subscribe to Updates
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default OurImpact;